name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: CI on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --verbose
      
    - name: Test
      run: cargo test --verbose
